name: Integration test

on: workflow_dispatch

jobs:
  mri_ruby_3_3_0:
    name: MRI Ruby 3.3.0 finds CVE-2024-27282
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'civisanalytics/ruby_audit'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      - name: Run RubyAudit and expect a nonzero exit code
        run: |
          set +e -o pipefail
          ./exe/ruby-audit check | tee output.txt
          [[ $? -ne 0 ]]
      - name: Expect advisory CVE-2024-27282 to be in the output
        run: |
          grep CVE-2024-27282 output.txt
  jruby_9_3_7:
    name: JRuby 9.3.7 finds CVE-2022-25857
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'civisanalytics/ruby_audit'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'jruby-9.3.7'
          bundler-cache: true
      - name: Run RubyAudit and expect a nonzero exit code
        run: |
          set +e -o pipefail
          ./exe/ruby-audit check | tee output.txt
          [[ $? -ne 0 ]]
      - name: Expect advisory CVE-2022-25857 to be in the output
        run: |
          grep CVE-2022-25857 output.txt
  rubygems_3_0_1:
    name: rubygems 3.0.1 finds CVE-2019-8325
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'civisanalytics/ruby_audit'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.1'
          # Cannot use `bundler-cache: true` here because we also want to install the RubyAudit gem
      - name: Install dependencies and the local RubyAudit gem
        run: |
          bundle install --jobs=3 --retry=3
          bundle exec rake install
      - name: Run RubyAudit and expect a nonzero exit code
        run: |
          set +e -o pipefail
          ruby -v
          gem -v
          ruby-audit check | tee output.txt
          [[ $? -ne 0 ]]
      - name: Expect advisory CVE-2019-8325 to be in the output
        run: |
          grep CVE-2019-8325 output.txt
